### ISSUE TITLE
TODO: Add any skills and make skill-switch

### ISSUE THREAD

**Issue by DARKSAYONE** [DARKSAYONE/SboxGameJam#6]
Добавить несколько разных скиллов(придумайти сами), добавить механику их активации и деактивации на персонаже.(Чтобы игрок условно мог подобрать его, а также и потерять). Также добавить селектор-скиллов по аналогии с селектором оружия в других играх.

- [ ] Добавить возможность "подобрать" новый скилл.
- [ ] Добавить селектор скиллов.
- [x] Добавить новые скиллы.
